const DATE_FORMAT_STRING = {
  DEFAULT: 'DD/MM/YYYY',
  DEFAULT_WITH_SLASH: 'DD-MM-YYYY',
  DEFAULT_WITH_SLASH_WITH_TIME: 'YYYY-MM-DD HH:mm',
  DATE_WITH_TIME: 'DD/MM/YYYY HH:mm A',
  DATE_WITH_MONTH_IN_SHORT_TEXT: 'DD MMM YYYY',
  DATE_WITH_YEAR_FIRST: 'YYYY-MM-DD',
  DATE_WITH_MONTH_FIRST: 'MM/DD/YYYY',
  DATE_WITH_MONTH_FIRST_WITH_TIME: 'MM/DD/YYYY HH:mm A',
  ONLY_MONTH_AND_DATE: 'DD-MM',
  ONLY_HOUR_MINUTE: 'HH:mm',
  MONTH_DAY_COMMA_YEAR: 'MMM DD, YYYY',
}

export default DATE_FORMAT_STRING
