import { PropsWithChildren } from 'react'
import { Analytics } from '@vercel/analytics/next'
import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'

import { DefaultPageProps } from '@/@types/locales'
import { getDictionary } from '@/share/dictionaries/get-dictionary'
import DictionaryProvider from '@/share/providers/dictionary-provider'

import Provider from './provider'

import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

async function RootLayout({ children, params }: PropsWithChildren<DefaultPageProps>) {
  const { locale } = await params
  const dictionary = await getDictionary(locale)

  return (
    <html lang={locale}>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Provider>
          <DictionaryProvider dictionary={dictionary} lang={locale}>
            {children}
          </DictionaryProvider>
        </Provider>
      </body>

      <Analytics />
    </html>
  )
}

export default RootLayout
